[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
mysql = "26.0.1"
serde = "1.0.219"
toml = "0.9.5"
governor = "0.10.1"
nonzero_ext = "0.3.0"

[profile.release]
opt-level = 3
